################################################################################
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################
version: '3.5'

networks:
  docker-mesos-cluster-network:
    name: docker-mesos-cluster-network

services:
  master:
    image: flink/docker-mesos-cluster:latest
    entrypoint: mesos-master
    container_name: "mesos-master"
    networks:
      docker-mesos-cluster-network:
        aliases:
          - mesos-master
    ports:
      - "8081:8081"
      - "5050:5050"
    volumes:
      - ${END_TO_END_DIR}:${END_TO_END_DIR}
      - ${FLINK_DIR}:${FLINK_DIR}
      - ${FLINK_LOG_DIR}:${FLINK_LOG_DIR}
      - ${MVN_REPO}:${MVN_REPO}
    environment:
      MESOS_PORT: 5050
      MESOS_QUORUM: 1
      MESOS_REGISTRY: in_memory
      MESOS_LOG_DIR: /var/log/mesos
      MESOS_WORK_DIR: /var/tmp/mesos
      FLINK_LOG_DIR: ${FLINK_LOG_DIR}

  slave:
    image: flink/docker-mesos-cluster:latest
    entrypoint: mesos-slave
    privileged: true
    depends_on:
      - master
    container_name: "mesos-slave"
    networks:
      - docker-mesos-cluster-network
    volumes:
      - ${END_TO_END_DIR}:${END_TO_END_DIR}
    environment:
      MESOS_RESOURCES: "cpus:${MESOS_AGENT_CPU}"
      MESOS_PORT: 5051
      MESOS_MASTER: mesos-master:5050
      MESOS_SWITCH_USER: 0
      MESOS_CONTAINERIZERS: mesos
      MESOS_LOG_DIR: /var/log/mesos
      MESOS_WORK_DIR: /var/tmp/mesos
      MESOS_SYSTEMD_ENABLE_SUPPORT: 'false'
      FLINK_LOG_DIR: ${FLINK_LOG_DIR}
